### ISSUE TITLE
[FEAT] Sparse Embedding을 사용한 Casename Classification

### ISSUE THREAD

**Issue by mjk0618** [boostcampaitech5/level3_nlp_finalproject-nlp-08#20]
## Background
- LLM 프롬프트 입력 시, query와 함께 casename을 입력하면 질문 의도에 맞는 대답을 할 것으로 예상됨
- query에 대한 casename이 현재는 구분되어있지 않기 때문에, 각 데이터를 clustering 수행 후 cluster마다 keyword 추출 후 casname class 부여

## Todo 
- [x] Sparse Embedding 또는 Dense Embedding으로 변환하는 코드 구현
- [ ] 여러 유사도 알고리즘을 사용하여 유사도(distance) 정량화
- [x] Clustering
- [ ] Keyword를 바탕으로 cluster마다 class 부여
