### ISSUE TITLE
[FIX] LLM훈련 코드,인퍼런스 타입 수정 및 데이터 전처리 코드 수정

### ISSUE THREAD

**Issue by taemin6697** [boostcampaitech5/level3_nlp_finalproject-nlp-08#26]
## Background
- 기존 LLM에서의 데이터 전처리 시 eos 토큰이 삽입되지 않아 inference시 max token만큼의 길이가 지속해서 출력되지 않았다.
- dataset의 drop column을 수동으로 직접 지정하는 불편함 존재
- eval을 추가함으로써 오버피팅 확인

## Todo 
- [x] <|endoftext|>을 토크나이징시 텍스트 단위에서의 삽입
- [x] 훈련시 eval_data 평가
- [x] concat_dataset을 만들때 자동으로 question,answer의 column을 가져오도록 수정
- [x] 인퍼런스 모델 로드를 torch_dtype=torch.float16 형식으로 불러오도록 수정
