### ISSUE TITLE
[FEAT] 답변 생성 API 구현

### ISSUE THREAD

**Issue by SangwonYoon** [boostcampaitech5/level3_nlp_finalproject-nlp-08#3]
## Background
- 질문 문장이 입력으로 주어지고, 답변 문장을 출력으로 생성하는 모델을 패키징하여 도커 이미지 생성

## Todo 
- [x] requirements.txt 작성
- [x] fastapi를 활용해 routing을 담당하는 main.py 구현
- [x] 모델이 답변을 생성하는 generate.py 구현
