### ISSUE TITLE
[FEAT] CI 파이프라인 구축

### ISSUE THREAD

**Issue by SangwonYoon** [boostcampaitech5/level3_nlp_finalproject-nlp-08#4]
## Background
- 코드 상의 문제를 조기에 파악할 수 있도록 CI 파이프라인을 구축

## Todo 
- [x] 테스트 코드 작성
- [x] workflow 파일 작성
- [x] self-hosted runner 등록
- [ ] CI 파이프라인 정상 작동 확인
