### ISSUE TITLE
[FEAT] 로드 밸런싱 적용

### ISSUE THREAD

**Issue by SangwonYoon** [boostcampaitech5/level3_nlp_finalproject-nlp-08#43]
## Background
- 트래픽을 다수의 서버에 분산하기 위한 로드 밸런싱 적용

## Todo 
- [x] V100 서버의 프록시 서버 역할을 할 EC2 구성
- [x] 로드 밸런싱을 진행할 ALB와 고정 IP를 위한 NLB 구축 및 연결
- [x] 웹 - 서버간 통신 테스트
