### ISSUE TITLE
[FEAT] LLM 모델 훈련 인퍼런스 코드 구현

### ISSUE THREAD

**Issue by taemin6697** [boostcampaitech5/level3_nlp_finalproject-nlp-08#7]
## Background
- LLM 모델 학습 인퍼런스 코드 구현 

## Todo 
- [x] train 코드 작성
- [x] inference 코드 작성
- [x] 텍스트 전처리 코드 작성
- [x] 코드 모듈화
