### ISSUE TITLE
[FEAT] BERT 기반 유사판례 코드 구현

### ISSUE THREAD

**Issue by taemin6697** [boostcampaitech5/level3_nlp_finalproject-nlp-08#9]
## Background
- BERT 기반 유사판례 코드 구현

## Todo 
- [x] inference 코드 작성
- [x] vector 데이터 생성 코드 작성
- [x] 판례 데이터 전처리 코드 작성
