### ISSUE TITLE
[FEAT] 포스트세션 수정

### ISSUE THREAD

**Issue by Kim-Ju-won** [boostcampaitech5/level3_nlp_finalproject-nlp-08#99]
## Background
- 전체 적인 코드 리팩토링 및 Document 수정

## Todo 
- [ ] README.md 수정
  - [x] 서비스 종료 안내 문구 추가
  - [x] 문법 검사
  - [x] 발표자료 추가
  - [x] 여백 조정
  - [ ] 모델 별 설명 추가
  - [x] 가독성 낮은 문구 수정
  - [ ] 사진 자료 수정
- [ ] 파트 별 Document 페이지 추가
  - [ ] BackEnd 파트 Document 추가
  - [ ] FrontEnd 파트 Document 추가
  - [ ] Data 파트 Document 추가
  - [ ] Model 파트 Document 추가
  - [ ] 페이지 설명 Document 추가
